<?php


declare(strict_types=1);



//'palettes' => [
//        '__selector__'   => ['loadDirectory'],
//        'default' => '{title_legend},title,class;{directory_legend:hide},loadDirectory;{publish_legend},published,start,stop',
//    ],
//    'subpalettes' => ['loadDirectory' => 'dirSRC,loadSubdir,extension,prefix,publishAll'],
//['TL_LANG']['tl_downloadarchive']['loadDirectory']

$GLOBALS['TL_LANG']['tl_downloadarchive']['title'] = ['Name', 'Assign a name to this download archive.'];
$GLOBALS['TL_LANG']['tl_downloadarchive']['class'] = ['CSS class', 'You can assign a css-class to this archive, which will be assigned to every file in the frontend.'];
$GLOBALS['TL_LANG']['tl_downloadarchive']['title_legend'] = 'Title';
$GLOBALS['TL_LANG']['tl_downloadarchive']['directory_legend'] = 'Read directory';

$GLOBALS['TL_LANG']['tl_downloadarchive']['loadDirectory'] = ['Load directory', 'This only works if there are no files connected to this download archive yet: Load the directory from the filesystem, this adds all files inside it. '];
$GLOBALS['TL_LANG']['tl_downloadarchive']['dirSRC'] = ['Select directory','Select the director to scan.'];

$GLOBALS['TL_LANG']['tl_downloadarchive']['loadSubdir'] = ['Scan subdirectories', 'Do you want to scan subdirectories?'];
$GLOBALS['TL_LANG']['tl_downloadarchive']['extension'] = ['File extension', 'You can limit the files to a specific extension. Separate several types with a comma.'];
$GLOBALS['TL_LANG']['tl_downloadarchive']['prefix'] = ['Use a prefix', 'You can autogenerate the tile of each element from this prefix string followed by a autogenerated number.'];
$GLOBALS['TL_LANG']['tl_downloadarchive']['publishAll'] = ['Auto publish all files', 'Automatically publish all files on initial import.'];
$GLOBALS['TL_LANG']['tl_downloadarchive']['publish_legend'] = 'Publish Archive';
$GLOBALS['TL_LANG']['tl_downloadarchive']['published'] = ['Publish Archive', 'Unless you choose this option the archive is not visible to the visitors of your website.'];
